# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 0 * * *'
  push: 
   branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 'Updating DB'
        run: curl https://scrapeanimefiller.herokuapp.com/schedule.json -d project=default -d spider=animefiller
